### ISSUE TITLE
Problem setting the endpoint to connect to my Next JS app

### ISSUE THREAD

**Issue by oboutarf** [GatoGraphQL/GatoGraphQL#2694]
Hello i try making request to my GatoGraphql custom endpoint from my nextJS app running headless.
Only i always have a 410 response status when i try making queries. Maybe i did something wrong in configuration on wordpress, but i followed your guide an everything looks fine.
Great plugin btw 🎉

**Comment by leoloso** [comment]
That's very weird, there must be something wrong with your site configuration, I don't think it's related to Gato GraphQL. It certainly never returns a 410 on its code.

Check if you have nice permalinks enabled (eg: /graphql/some-custom-endpoint instead of ?p=8439), if you can load that CPT URL in the browser (eg: https://yoursite.com/graphql/some-custom-endpoint,  and also passing ?view=schema and ?view=graphiql), try being logged-in and logged-out, and others.

Also try loading other CPTs from Gato GraphQL (eg: persisted query), and from other plugins too.

Maybe there's some conflict with some other plugin? Try disabling all other plugins; if it starts working, enable them one by one until finding out which one creates the conflict (and if so, let me know which one it is)

**Comment by leoloso** [comment]
You can also test modifying the Gato GraphQL settings for the Custom Endpoint base url, switching from "graphql" to something else.

Btw, are you typing the URL of the endpoint, and as such maybe there was a typo? Or clicking on the link? (in the Custom Endpoints CPT table, on hover on each entry, it provides the link to the endpoint)

**Comment by leoloso** [comment]
@oboutarf Any news with this?

**Comment by leoloso** [comment]
Btw, there was a problem with PHP 8.2, and I just fixed it (#2743). I wonder if your issue is the same one?

You can check using the latest DEV `gatographql-4.0.0-dev` plugin:  https://github.com/GatoGraphQL/GatoGraphQL/actions/runs/10037214940

**Comment by leoloso** [comment]
Fixed in `v4.0.0`
