### ISSUE TITLE
Re-add "Tested up to WP 6.6"

### ISSUE THREAD

**Issue by leoloso** [GatoGraphQL/GatoGraphQL#2710]
Blocks are not loaded in WordPress 6.6 RC1. Hence, removed the "Tested up to: 6.6" tag in `readme.txt`

Add it again when the issue is fixed.

**Comment by leoloso** [comment]
If need to update the `@wordpress` scripts, this is currently the list of them:

```
"@wordpress/block-editor": "^4.3.0"
"@wordpress/components": "^10.0.0"
"@wordpress/i18n": "^3.14.0"
"@wordpress/scripts": "^12.1.0"
"@wordpress/compose": "^3.19.0"
"@wordpress/scripts": "^12.1.0
"@wordpress/data": "^4.22.0"
"@wordpress/icons": "^2.10.2"
"@wordpress/edit-post": "^3.21.0"
"@wordpress/plugins": "^2.20.0"
"@wordpress/base-styles": "^2.0.0"
```

**Comment by leoloso** [comment]
This is the new Schema Configuration screen with WP 6.6 RC1:

![Screenshot 2024-07-01 at 16-20-13 Add New GraphQL Schema Configuration ‹ Gato GraphQL — WordPress](https://github.com/GatoGraphQL/GatoGraphQL/assets/1981996/5961b971-0a68-46c6-abc9-a5e4fdeb8b8d)

**Comment by swissspidy** [comment]
@leoloso I'd love to help you with this issue but I can't for the life of me figure out how to set up your giant monorepo for some debugging.

Anyway, your code is using generators and for some reason is built targeting older browsers (IE 11) which don't support generators and thus is expecting `regenerator-runtime` to be present. WP 6.6 no longer loads that dependency by default via `wp-polyfill`.
You can address this by either a) manually adding `regenerator-runtime` as a dependency to your scripts or b) update your babel/webpack config so that generator functions are not transpiled to use regenerator.

Meanwhile I am working on a fix for `@wordpress/dependency-extraction-webpack-plugin` to ensure `regenerator-runtime` is added automatically again for such a case.

**Comment by leoloso** [comment]
Thanks @swissspidy 

I've redone the data stores without generators (https://github.com/WordPress/gutenberg/issues/63009#issuecomment-2209178124), even though now I encountered a new issue (https://github.com/WordPress/gutenberg/issues/63135).

Once that one is solved, I'll take care of adding the "Tested up to WP 6.6" tag again.

Btw, if you still want to set-up this giant monorepo, are you're having issues, I can help you (do you have Lando installed?). Just let me know
