### ISSUE TITLE
How to query any page by path like nodeByUri from WP Graphql?

### ISSUE THREAD

**Issue by cguagenti** [GatoGraphQL/GatoGraphQL#2745]
## Detailed description
Wow! First of all, congrats on this amazing piece of art.
I'm currently using WP GraphQL with nodeByUri and was wondering if it is something possible with Gato as well. More specifically, I would like to resolve any URL through Gato in order to use a catch-all approach in my app (home, taxonomies, CPT, etc...).

## Context
I would like to query any URL like I can with WP GraphQL ([nodeByUri](https://www.wpgraphql.com/2021/12/23/query-any-page-by-its-path-using-wpgraphql))

**Comment by leoloso** [comment]
Hi, there's no `nodeByUri` field to catch for all different entities (pages, categories, etc), but you can query by `slug` or `path` or whatever is suitable for each of them.

For instance, you can query a page by its path:

```graphql
{
  page(by: { path: "some-path/to/the/page" }) {
    id
    title
  }
}
```

**Comment by cguagenti** [comment]
Thanks @leoloso for the quick response!

Unfortunately, I can't do that because I need a resolver like WordPress does, so I can have custom taxonomies and CPT without any prefixes on the frontend (Next.js).

Happy to get my hands dirty, so if you can share any tips on where to start, I would appreciate it.

**Comment by leoloso** [comment]
You mean you want to implement `nodeByUri` in Gato GraphQL?

I don't think it's possible, because Gato GraphQL natively uses the same ID as in WordPress for all entities, instead of using a new "GraphQL ID".

Because of this, whenever you return a `Union` type, all elements in that union need to be uniquely identifiable by their ID. However, if `nodeByUri` returns `Post | User`, then it's not uniquely identifiable, because both a post and a user can have ID `1`.

(That's the trade-off from using WordPress IDs for GraphQL objects too).

**Comment by cguagenti** [comment]
That makes sense.

What about a seed query that returns the types of the request? Then make another query specifically for that entity, either with @depends, @include, and @export, or have some JS logic that makes a query based on the seed similar to what FaustJS is doing.

Would that work?

For example:

```gql
query seedRequestUri($uri: String!) {
  isHome: _echo(value: false) @export(as: "isHome")
  isTerm: _echo(value: false) @export(as: "isTerm")
  isCustomPost: _echo(value: false) @export(as: "isCustomPost")
  isSearch: _echo(value: false) @export(as: "isSearch")

  seedRequest(uri: $uri) {
    isHome: _echo(value: true) @export(as: "isHome")
    isTerm: _echo(value: true) @export(as: "isTerm")
    isCustomPost: _echo(value: true) @export(as: "isCustomPost")
    isSearch: _echo(value: true) @export(as: "isSearch")
    id @export(as: "id")
  }
}


query getCustomPost @depends(on: "seedRequestUri") @include(if: $isCustomPost) {
  customPost(by: { id: $id}) {
    __typename
    ... on GenericCustomPost {
      id
      blocks
    }
    ... on Post {
      id
      blocks
    }
    ... on Page {
      id
      blocks
    }
  }
}

query getTerm @depends(on: "seedRequestUri") @include(if: $isTerm) {}
query getSearch @depends(on: "seedRequestUri") @include(if: $isSearch) {}
```

Ideally this would be done in 2 separated query so in a headless scenario we could cache the seed query (with LRU, Redis, etc...), and run the others instantly.

**Comment by leoloso** [comment]
Yes, something like that could work.

Btw, there's interface `CustomPost` implemented by `GenericCustomPost`, `Post` and `Page`, so that query could be simpliifed:

```graphql
query getCustomPost @depends(on: "seedRequestUri") @include(if: $isCustomPost) {
  customPost(by: { id: $id}) {
    __typename
    ... on CustomPost {
      id
      blocks
    }
  }
}
```

But then, you can make it even simpler, adding input `by: { uri: ... }` on all the selectors, and whichever is suitable will return the entity, while the other ones will be `null`:

```graphql
query GetEntityByURI(
  $uri: String!
) {
  post(by: { uri: $uri }) {
    id
    blocks
  }
  page(by: { uri: $uri }) {
    id
    title
  }
  postCategory(by: { uri: $uri }) {
    id
    name
  }
  postTag(by: { uri: $uri }) {
    id
    name
  }
  user(by: { uri: $uri }) {
    id
    displayName
  }
}
```

and this may return:

```json
{
  "data": {
    "post": null,
    "page": {
      "id": 2,
      "title": "Some title"
    },
    "postCategory": null,
    "postTag": null,
    "user": null
  }
}
```

Concerning the Search page, if you can identify it's a search page in your JS, then you can extract the search term and pass it to the query:

```graphql
query Search(
  $searchTerm: String!
) {
  posts(filter: { search: $searchTerm }) {
    id
    blocks
  }
}
```

**Comment by leoloso** [comment]
Hi @cguagenti are you planning to work on this issue? If you're not, I'll close it

**Comment by leoloso** [comment]
Anyone interested in implementing this, be welcome to request reopening the issue
